apiVersion: v1
kind: Pod
metadata:
  name: dispatch
  labels:
    component: dispatch
spec:
  containers:
    - name: frontend
      image: 481679057437.dkr.ecr.us-east-1.amazonaws.com/user:1.0.0

---
apiVersion: v1
kind: Service
metadata:
  name: dispatch
spec:
  selector:
    component: dispatch
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
